import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SWRConfig } from 'swr';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased layout bg-gray-50`}
      >
        <SWRConfig
          value={{
            fallback: {
              // We do NOT await getUser() here
              // Only components that read this data will suspend
              //'/api/user': getUser(),
            },
          }}
        >
          <Header />
          <main className="h-full min-h-screen flex flex-col">
            {children}
          </main>
          <Footer />

        </SWRConfig>
      </body>
    </html>
  );
}
