import type { Metadata } from "next";
import "@/app/globals.css";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashbordLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="bg-amber-50 p-0 flex-grow">
            {children}
        </div>
    );
}
